name: Linting and Formatting on PR
on:
  pull_request:
    branches:
      - main

jobs:
  Continuous-Integration:
    name: Performs linting, formatting on the application
    runs-on: ubuntu-latest
    steps:
      - name: Print name
        run: echo "Hello. $BUILD. My API_KEY is ${{secrets.API_KEY}}"
        env:
          BUILD: 'We are currently running the Build job'
    
